spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 711006759210-5udg0i8dvqpkc3l9d9h6s2l222l8olv7.apps.googleusercontent.com
            client-secret: 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

jwt:
  secretKey: asrjokgynmyokqwgvtyoplsf4gl7oc23plaarfmflsgkynjbjkfnkdng
