spring.application.name=springSecurity

spring.datasource.url=jdbc:mysql://localhost:3306/prod-ready
spring.datasource.username=root
spring.datasource.password=vijay
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect



#spring.security.user.name = vijay
#spring.security.user.password = password


#jwt.secretKey = asrjokgynmyokqwgvtyoplsf4gl7oc23plaarfmflsgkynjbjkfnkdng
#711006759210-5udg0i8dvqpkc3l9d9h6s2l222l8olv7.apps.googleusercontent.com
#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